name: Validate XML Schemas and Examples

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
      - name: Validate example against core schema
        run: xmllint --noout --schema core/pbb-core.xsd examples/schema-demo.xml || true
